### ISSUE TITLE
LANDING for Ads

### ISSUE THREAD

**Issue by ricardoaj20003** [ricardoaj20003/bikes#45]
We need to make a smaller version of the home for the ads.
![Landing](https://user-images.githubusercontent.com/6520979/54835465-bd325880-4c87-11e9-8c26-6f33711811a4.jpg)

**Comment by rahxd1** [comment]
Full page
URL-Local
http://localhost:3003/landing

![localhost_3003_landing](https://user-images.githubusercontent.com/3867666/55187157-ea867700-515d-11e9-9c3e-a8ee9723acee.png)
