### ISSUE TITLE
CART Form

### ISSUE THREAD

**Issue by ricardoaj20003** [ricardoaj20003/bikes#47]
http://beta.donmandon.mx/solicita

Validate field for only numbers.
![6fd51863-b35e-436b-9134-5b40bafc3ccb](https://user-images.githubusercontent.com/6520979/54835787-7b55e200-4c88-11e9-9eb6-703e5508a490.jpg)

**Comment by rahxd1** [comment]
Solved only numbers
![Screen Shot 2019-03-28 at 12 13 08 PM](https://user-images.githubusercontent.com/3867666/55182240-df7a1980-5152-11e9-9577-7b13706fb981.png)
