### ISSUE TITLE
CAPTCHA 

### ISSUE THREAD

**Issue by ricardoaj20003** [ricardoaj20003/bikes#48]
¿Can we remove this and only put the check box as the captcha?

![15257524-ab19-426f-8cf9-4784cb1b3da9](https://user-images.githubusercontent.com/6520979/54835849-99bbdd80-4c88-11e9-8bfb-836341bee99a.jpg)

**Comment by rahxd1** [comment]
No, this can not be done for reasons of the captcha itself
