### ISSUE TITLE
Mouse Flow Install

### ISSUE THREAD

**Issue by ricardoaj20003** [ricardoaj20003/bikes#49]
`<script type="text/javascript">
    window._mfq = window._mfq || [];
    (function() {
        var mf = document.createElement("script");
        mf.type = "text/javascript"; mf.async = true;
        mf.src = "//cdn.mouseflow.com/projects/8f08a3b3-499d-4895-b8ec-b4ec3875b096.js";
        document.getElementsByTagName("head")[0].appendChild(mf);
    })();
</script>`

**Comment by rahxd1** [comment]
Complete.!
![Screen Shot 2019-03-28 at 12 58 52 PM](https://user-images.githubusercontent.com/3867666/55185088-40a4eb80-5159-11e9-8980-1d1d3faea783.png)
