### ISSUE TITLE
MAP Hours

### ISSUE THREAD

**Issue by ricardoaj20003** [ricardoaj20003/bikes#50]
Block Maps for after hours of service.
From 9:00 to 5:40 P.M. block the map button and ad a alert that says "
Also from Monday to Friday the map will be available.

**Comment by rahxd1** [comment]
![Screen Shot 2019-03-28 at 12 56 35 PM](https://user-images.githubusercontent.com/3867666/55185023-1fdc9600-5159-11e9-9927-3df8431b84bd.png)
